name: NP21WSY Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: self-hosted
    timeout-minutes: 30

    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        Write-Host "=== Environment Check ==="
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Available tools:"
        
        # Check Visual Studio installation
        $vsPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
        if (Test-Path $vsPath) {
          Write-Host "✅ Visual Studio 2022 found"
        } else {
          Write-Host "❌ Visual Studio 2022 not found at expected location"
        }
        
        # Check for existing tools
        try { 
          $nasmVersion = & nasm -version 2>$null
          Write-Host "✅ NASM: $nasmVersion"
        } catch { 
          Write-Host "❌ NASM not found in PATH" 
        }
        
        try { 
          $yasmVersion = & yasm --version 2>$null
          Write-Host "✅ YASM: $yasmVersion"
        } catch { 
          Write-Host "❌ YASM not found in PATH" 
        }

    - name: Initialize Visual Studio environment
      run: |
        cmd /c "call `"${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat`" && set" | ForEach-Object {
          if ($_ -match "^([^=]+)=(.*)") {
            [Environment]::SetEnvironmentVariable($matches[1], $matches[2])
          }
        }

    - name: Verify project file
      run: |
        cd win9x
        if (Test-Path "np2vs2019.vcxproj") {
          Write-Host "✅ Project file found"
          Get-Content np2vs2019.vcxproj | Select-String "PlatformToolset" | Select-Object -First 3
        } else {
          Write-Host "❌ Project file not found, listing directory:"
          Get-ChildItem
        }

    - name: Build NP21WSY
      run: |
        cd win9x
        Write-Host "=== Building NP21WSY ==="
        Write-Host "Platform: ${{ matrix.platform }}"
        Write-Host "Configuration: ${{ matrix.configuration }}"
        
        # Use local MSBuild with full Visual Studio environment
        msbuild np2vs2019.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143 /verbosity:normal

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: np21wsy-${{ matrix.platform }}-${{ matrix.configuration }}
        path: |
          bin/
          !bin/**/*.pdb
          !bin/**/*.ilk
