name: NP21WSY Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1

    - name: Setup YASM
      run: |
        $yasmUrl = "https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0-win64.exe"
        Invoke-WebRequest -Uri $yasmUrl -OutFile "yasm.exe" -UseBasicParsing
        New-Item -ItemType Directory -Force -Path "C:\yasm"
        Move-Item yasm.exe C:\yasm\yasm.exe
        echo "C:\yasm" >> $env:GITHUB_PATH

    - name: Verify project file
      run: |
        cd win9x
        if (Test-Path "np2vs2019.vcxproj") {
          Write-Host "Project file found"
          Get-Content np2vs2019.vcxproj | Select-String "PlatformToolset" | Select-Object -First 3
        } else {
          Write-Host "Project file not found, listing directory:"
          Get-ChildItem
        }

    - name: Build NP21WSY
      run: |
        cd win9x
        msbuild np2vs2019.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /verbosity:minimal

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: np21wsy-${{ matrix.platform }}-${{ matrix.configuration }}
        path: |
          bin/
          !bin/**/*.pdb
          !bin/**/*.ilk
