name: NP21WSY Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1

    - name: Setup YASM
      run: |
        Invoke-WebRequest -Uri "http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe" -OutFile "yasm.exe"
        New-Item -ItemType Directory -Force -Path "C:\yasm"
        Move-Item yasm.exe C:\yasm\yasm.exe
        echo "C:\yasm" >> $env:GITHUB_PATH

    - name: Build NP21WSY
      run: |
        cd win9x
        msbuild np2vs2019.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: np21wsy-${{ matrix.platform }}-${{ matrix.configuration }}
        path: |
          bin/
          !bin/**/*.pdb
          !bin/**/*.ilk
